---
title: "TP1"
author: "MOHAMED_AHMED_MOHAMED_LEMINE ~~ CHRIF M'HAMEDOU"
documentclass: article
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

<!-- see help at https://bookdown.org/yihui/rmarkdown-cookbook/latex-output.html -->

```{r setup, include=FALSE, message=FALSE}
#see full list >knitr::opts_chunk$get()
knitr::opts_chunk$set(echo = TRUE, fig.align="center", prompt = TRUE, comment="")
```


# Exercise 1 -- copule logistique

$$
C(u,v) = 1/(1/u+1/v-1)
$$

## Question 1

On a $V|U=u$ a pour FDR 
$$
F_{V|U=u}(v) = \frac{1}{ (1+\frac{u}{v} - u)^2 }
$$

donc on trouve l'inverse de FDR de $V|U=u$

$$
F^{-1}_{V|U=u}(p) = \frac{u}{u - 1 +  \frac{1}{\sqrt{p}}}
$$






## Question 2
```{r}
rcoplogis <- function(n) {
  u <- runif(n)
  w <- runif(n)
  v <- u / (u - 1 + 1/sqrt(w))
  return(cbind(u,v))
}

res <- rcoplogis(1000)
plot(res)
```




## Question 3
```{r}
mecdf <- function(xy)
{
  f <- function(x,y)
  {
    mean(xy[, 1] <= x & xy[, 2] <= y)
  }
  Vectorize(f, c("x", "y"))
  
}
```



## Question 4

```{r}
pcoplogis <- function(u,v) {
  res <- 1 / (1/u + 1/v -1)
  return(res)
}

```


## Question 5

```{r}
grille <- cbind(1/1:10, 1/2:11)

uv1 <- rcoplogis(1000)
plot(uv1)
cbind("theo"=pcoplogis(grille[,1] , grille[,2]), 
      "emp"=mecdf(uv1)(grille[,1] , grille[,2]))


```


## Question 6

```{r}
m <- 100
verif <- cbind(runif(m) , runif(m))
simu <- rcoplogis(1000)

error <- function(verif , simu) 
{
    ptheao <- pcoplogis(grille[,1] , grille[,2])
    pemp <- mecdf(uv1)(grille[,1] , grille[,2])
    mean(abs(ptheao - pemp))
} 

error(verif , simu)
```


## Question 7


```{r}
# install.packages("copula")
library(copula)
#?fitLambda
uv1 <- rcoplogis(1e5)
 # Lambda L 
fitLambda(uv1)[1,2]
 # Lambda R 
fitLambda(uv1 , lower = FALSE)[1,2]
```


## Question 8

```{r}

```


## Question 9

```{r}
library(copula)
n <- 1e3
uv1 <- rcoplogis(n)
C.hat <- empCopula(uv1, smoothing = "beta")

contourplot2(C.hat, FUN=dCopula, main="niveaux de densité",
        col.regions=colorRampPalette( c("white", "green", "yellow", "orange", "red") )(16))

n.col <- 100
mycolpal <- colorRampPalette( c("white","green", "yellow", "orange", "red") )(n.col)
n.grid <- 26
zmat <- as.matrix(expand.grid(seq(0, 1, length=n.grid),
                              seq(0, 1, length=n.grid)))
zmat <- matrix(dCopula(zmat, C.hat), ncol=n.grid)
nrz <- nrow(zmat)
ncz <- ncol(zmat)
zctr <- zmat[-1, -1] + zmat[-1, -ncz] + zmat[-nrz, -1] + zmat[-nrz, -ncz]
# Recode facet z-values into color indices
facetcol <- cut(zctr, n.col)

persp(C.hat, FUN=dCopula, col=mycolpal[facetcol], n.grid=n.grid)

```


## Question 10

```{r}

```























